export const environment = {
  SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL || "",
  SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || "",
  SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY || "",
  SUPABASE_PUBLISHABLE_KEY: process.env.SUPABASE_PUBLISHABLE_KEY || "",
  APP_VERSION: process.env.NEXT_PUBLIC_APP_VERSION || "",
  MIDTRANS_API_URL: process.env.NEXT_PUBLIC_MIDTRANS_API_URL || "",
  MIDTRANS_API_CLIENT_KEY:
    process.env.NEXT_PUBLIC_MIDTRANS_API_CLIENT_KEY || "",
  MIDTRANS_SERVER_KEY: process.env.MIDTRANS_SERVER_KEY || "",
};
